# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# NOTE: The actual Flutter project is in the faith_connect/ subdirectory.
# This root-level analysis_options.yaml excludes root-level Dart files
# to prevent false errors. Use faith_connect/analysis_options.yaml
# for the actual project analysis.

analyzer:
  # Exclude root-level Dart files since the actual Flutter project is in faith_connect/
  exclude:
    - "lib/**"
    - "test/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "faith_connect/**"  # Exclude to avoid duplicate analysis
