// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// A placeholder class that provides default Firebase options for use with
/// `Firebase.initializeApp`.
///
/// If you use the flutter pub get` or `flutter pub upgrade` command, this
/// class is automatically updated with the latest Firebase configuration of
/// your Firebase project.
///
/// To reconfigure this file as per your Firebase project settings,
/// run the FlutterFire configure command.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbAIyosoI0C5WhKu75PsT9PL0fA7a87Ec',
    appId: '1:476724277712:web:4a5d3d61d4a157e2e049d5',
    messagingSenderId: '476724277712',
    projectId: 'faithconnect-fe032',
    storageBucket: 'faithconnect-fe032.firebasestorage.app',
    authDomain: 'faithconnect-fe032.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbAIyosoI0C5WhKu75PsT9PL0fA7a87Ec',
    appId: '1:476724277712:android:4a5d3d61d4a157e2e049d5',
    messagingSenderId: '476724277712',
    projectId: 'faithconnect-fe032',
    storageBucket: 'faithconnect-fe032.firebasestorage.app',
    authDomain: 'faithconnect-fe032.firebaseapp.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbAIyosoI0C5WhKu75PsT9PL0fA7a87Ec',
    appId: '1:476724277712:ios:4a5d3d61d4a157e2e049d5',
    messagingSenderId: '476724277712',
    projectId: 'faithconnect-fe032',
    storageBucket: 'faithconnect-fe032.firebasestorage.app',
    authDomain: 'faithconnect-fe032.firebaseapp.com',
    iosBundleId: 'com.faithconnect.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbAIyosoI0C5WhKu75PsT9PL0fA7a87Ec',
    appId: '1:476724277712:ios:4a5d3d61d4a157e2e049d5',
    messagingSenderId: '476724277712',
    projectId: 'faithconnect-fe032',
    storageBucket: 'faithconnect-fe032.firebasestorage.app',
    authDomain: 'faithconnect-fe032.firebaseapp.com',
    iosBundleId: 'com.faithconnect.app',
  );
}
